name: warehouse_app
description: Warehouse inventory management application

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^0.5.1
  cloud_functions: ^0.6.0+1
  firebase_auth: ^0.18.2
  google_sign_in: ^4.5.5

  flutter_bloc: ^6.0.6
  equatable: ^1.2.5
  get_it: ^5.0.1
  formz: ^0.3.0
  path_provider: ^1.6.24
  connectivity: ^2.0.2
  shared_preferences: ^0.5.12+4

  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
    - assets/google_logo.png
